### ISSUE TITLE
Pencarian menampilkan output yang tidak perlu

### ISSUE THREAD

**Issue by darkun7** [Pemrograman-Fasilkom-Unej/Bot-NIM-Universitas-Jember#9]
**Reproduksi**
Menjalankan perintah `/nim ma`

**Output**
```
NIM = NIM
NAMA =  NAMA
============================
NIM = 182410101002
NAMA =  RAHMAT INDRAWAN
============================
NIM = 182410101006
NAMA =  SUCI DWI MAYSAROH
============================
```

**Seharusnya**
Output seperti:
```
NIM = NIM
NAMA =  NAMA
```
Tidak perlu ditampilkan

**Comment by darkun7** [comment]
Hal ini juga berlaku untuk pencarian
`/nim nim`

**Dugaan**
Terdapat record dengan nilai NIM & NAMA saat diexport.

**Comment by evaleries** [comment]
Sepertinya salah bot,
yang kamu coba disini botnya [NIM Fasilkom UNEJ Finder @nimfasilkom_bot](https://t.me/nimfasilkom_bot)

Sedangkan bot untuk repository ini yaitu [Bot NIM Universitas Jember @nim_unej_bot](https://t.me/nim_unej_bot)

Penyebabnya tidak ada info mengenai username bot di repository ini 😅.
Thanks anyway
